const list = [
  {
    id: 1,
    title: "Shirt",
    desc: "Color: Black  | Size : XXL , M , S",
    price: 89,
    img: 'http://images.asos-media.com/products/asos-design-skinny-western-denim-jacket-in-black/12887167-1-black?$n_480w$&wid=476&fit=constrain',
    
    amount: 1,
    
  },
  {
    id: 2,
    title: " Sweatshirt",
    desc: "Color: Yellow  | Size : XXL , M , S",
    price: 98,
    img: "https://lp2.hm.com/hmgoepprod?set=source[/2d/96/2d96be844c3acb2129b5914a783f1b7ad158fd3e.jpg],origin[dam],category[],type[DESCRIPTIVESTILLLIFE],res[y],hmver[2]&call=url[file:/product/main]",
    amount: 1,
  },
  {
    id: 3,
    title: "Cargo joggers",
    desc: "Color: Black | Size : XXL , M , S",
    price: 143,
    img: "https://lp2.hm.com/hmgoepprod?set=source[/b2/5d/b25df154049847b8cc930f44aa5a0e9175cf4a81.jpg],origin[dam],category[],type[DESCRIPTIVESTILLLIFE],res[y],hmver[2]&call=url[file:/product/main]",
    amount: 1,
  },
  {
    id: 4,
    title: " Pure Cotton Casual Shirt",
    desc: "Color: Brown | Size : XXL , M , S",
    price: 57,
    img: "https://lp2.hm.com/hmgoepprod?set=source[/ab/ac/abaca336eb0b95da2d27b8abe6c3e02105ecf541.jpg],origin[dam],category[men_jacketscoats_shirtjackets],type[DESCRIPTIVESTILLLIFE],res[y],hmver[2]&call=url[file:/product/main]",
    amount: 1,
  },
  {
    id: 5,
    title: "Slim Mom High Ankle Jeans",
    desc: "Color: Blue  | Size : XXL , M , S",
    price: 149,
    img: "https://lp2.hm.com/hmgoepprod?set=source[/dc/77/dc77bcec6f1bd9d93e3236a172efa05d189a7149.jpg],origin[dam],category[],type[DESCRIPTIVESTILLLIFE],res[y],hmver[2]&call=url[file:/product/main]",
    amount: 1,
  },
  {
    id: 6,
    title: "Relaxed Fit Hoodie",
    desc: "Color: Pink  | Size : XXL , M , S",
    price: 135,
    img: "https://lp2.hm.com/hmgoepprod?set=source[/78/b3/78b372870d6d6043480ba678c8eac9b90729d29c.jpg],origin[dam],category[],type[DESCRIPTIVESTILLLIFE],res[y],hmver[2]&call=url[file:/product/main]",
    amount: 1,
  },
  {
    id: 7,
    title: "Oversized cotton T-shirt ",
    desc: "Color: LightBlue  | Size : XXL , M , S",
    price: 693,
    img: "https://lp2.hm.com/hmgoepprod?set=source[/94/52/9452c146b6f0ea0bf765de1da8a4cfcefc5a438c.jpg],origin[dam],category[men_tshirtstanks_shortsleeve],type[DESCRIPTIVESTILLLIFE],res[y],hmver[2]&call=url[file:/product/main]",
    amount: 1,
  },
  {
    id: 8,
    title: "Regular Fit sweatshirt shorts",
    desc: "Color: Red  | Size : XXL , M , S",
    price: 289,
    img: "https://lp2.hm.com/hmgoepprod?set=source[/38/e6/38e68645657f06ccd065a2ccc12fc2ba9035614f.jpg],origin[dam],category[],type[DESCRIPTIVESTILLLIFE],res[y],hmver[2]&call=url[file:/product/main]",
    amount: 1,
  },
  {
    id: 9,
    title: "Slim Fit Twill trousers ",
    desc: "Color: White | Size : XXL , M , S",
    price: 80,
    img: "https://lp2.hm.com/hmgoepprod?set=source[/57/b7/57b70a912c45d5364052ee6c6334b017ed58afe4.jpg],origin[dam],category[men_trousers_trousers_slim_all],type[DESCRIPTIVESTILLLIFE],res[y],hmver[2]&call=url[file:/product/main]",
    amount: 1,
  },
  {
    id: 10,
    title: "Slim Fit Cropped cotton chinos",
    desc: "Color: Black  | Size : XXL , M , S",
    price: 86,
    img: "https://lp2.hm.com/hmgoepprod?set=source[/15/3e/153e4c4e920054a0ef1f1207fba6d6bc641e47aa.jpg],origin[dam],category[],type[DESCRIPTIVESTILLLIFE],res[y],hmver[2]&call=url[file:/product/main]",
    amount: 1,
  },
  {
    id: 11,
    title: "Regular Fit Printed T-shirt",
    desc: "Color: White  | Size :  M , S",
    price: 120,
    img: "https://lp2.hm.com/hmgoepprod?set=source[/cb/1f/cb1f3b58b3d50cc370dd30439e4e68b6433390b1.jpg],origin[dam],category[],type[DESCRIPTIVESTILLLIFE],res[y],hmver[2]&call=url[file:/product/main]",
    amount: 1,
  },
  {
    id: 12,
    title: "Regular Fit Cotton shorts",
    desc: "Color: Green | Size : XXL , M ",
    price: 157,
    img: "https://lp2.hm.com/hmgoepprod?set=source[/12/bd/12bd0acb457aa2f5d777f5422bc82800a09f2606.jpg],origin[dam],category[],type[DESCRIPTIVESTILLLIFE],res[y],hmver[2]&call=url[file:/product/main]",
    amount: 1,
  },
];

export default list;
